# Unit 06 — NumPy & Pandas Fundamentals
### Stage 1: Core Foundations | Data Science & AI Program

**Business scenario:** AdventureWorks, a fictional e-commerce company selling electronics, home products, and accessories.

**Audience:** Learners who completed Units 01–05  
**Environment:** Python 3 · Google Colab / Jupyter Notebook  

> **Instructor note:** This unit bridges core Python and data analysis. Students learn to work with numeric arrays and tabular data, inspect data quality, filter records, create features, summarize results, and prepare a dataset for later machine-learning work.

## Learning outcomes

By the end of this unit, you should be able to:
- Explain why NumPy and Pandas are useful for data analysis.
- Create and inspect NumPy arrays, including shape, dimensions, and data types.
- Perform basic vectorized calculations and Boolean filtering with NumPy.
- Create and inspect Pandas DataFrames.
- Select columns and rows with column selection, `.loc`, and `.iloc`.
- Filter rows with one or more conditions.
- Create columns from existing data.
- Detect and handle missing values and duplicate records.
- Group records to produce simple business summaries.
- Import and export a CSV file.
- Explain how these skills support later data preparation and machine learning.

### Prerequisites
Variables, basic types, lists, dictionaries, conditions, loops, functions, and introductory file handling.

### Scope
This is an introductory unit. Advanced broadcasting, joins, time-series analysis, visualization, statistical inference, and machine-learning models are outside this notebook.

## Table of contents
1. AdventureWorks dataset and business questions
2. Why NumPy and Pandas?
3. NumPy arrays
4. DataFrames
5. Dataset inspection
6. Selecting rows and columns
7. Filtering
8. Creating columns
9. Missing values and duplicates
10. Grouping and summaries
11. CSV input/output
12. Integrated challenge
13. Instructor answer key
14. Summary and readiness checklist

## 1. AdventureWorks dataset and business questions

Each row represents an order line. The columns describe the order, customer, product, quantity, price, and status. A few records will be used later to demonstrate data-quality checks.

The data is synthetic and intentionally small so we can focus on the concepts.

In [4]:
import numpy as np
import pandas as pd

orders_data = {
    "order_id": ["AW-4101", "AW-4102", "AW-4103", "AW-4104", "AW-4105", "AW-4106", "AW-4107", "AW-4107"],
    "customer": ["Maya Chen", "Omar Saleh", "Lina Haddad", "Noah Reed", "Maya Chen", "Sara Nasser", "Omar Saleh", "Omar Saleh"],
    "category": ["Accessories", "Electronics", "Home", "Accessories", "Electronics", "Home", "Accessories", "Accessories"],
    "product": ["Wireless Mouse", "Mechanical Keyboard", "Desk Lamp", "USB-C Hub", "Headphones", "Desk Lamp", "Laptop Stand", "Laptop Stand"],
    "quantity": [2, 1, 2, 1, 1, 3, 2, 2],
    "unit_price": [24.99, 79.50, 28.75, 34.00, 59.99, 28.75, 39.00, 39.00],
    "status": ["Shipped", "Processing", "Shipped", "Cancelled", "Processing", "Shipped", "Processing", "Processing"]
}

orders = pd.DataFrame(orders_data)
display(orders)

,order_id,customer,category,product,quantity,unit_price,status
0,AW-4101,Maya Chen,Accessories,Wireless Mouse,2,24.99,Shipped
1,AW-4102,Omar Saleh,Electronics,Mechanical Keyboard,1,79.50,Processing
2,AW-4103,Lina Haddad,Home,Desk Lamp,2,28.75,Shipped
3,AW-4104,Noah Reed,Accessories,USB-C Hub,1,34.00,Cancelled
4,AW-4105,Maya Chen,Electronics,Headphones,1,59.99,Processing
5,AW-4106,Sara Nasser,Home,Desk Lamp,3,28.75,Shipped
6,AW-4107,Omar Saleh,Accessories,Laptop Stand,2,39.00,Processing
7,AW-4107,Omar Saleh,Accessories,Laptop Stand,2,39.00,Processing

### Business questions
- How many records are present?
- Which orders are still processing?
- What is the value of each order line?
- Which categories have the highest total line value?
- Are there missing or duplicate records that need attention?

**Data note:** Line value is quantity multiplied by unit price. It is not automatically official revenue: discounts, tax, returns, cancelled orders, and duplicate records may need separate rules.

## 2. Why NumPy and Pandas?

- **NumPy** provides efficient arrays and numerical operations.
- **Pandas** provides labeled tabular data structures, especially `Series` and `DataFrame`.

Python lists are flexible general-purpose containers. NumPy arrays are designed for numerical operations on arrays of compatible values. Pandas makes it easier to explore and transform tables with named columns.

In [5]:
sample_quantities = [2, 1, 2, 1]
quantity_array = np.array(sample_quantities)

print(f"Python list: {sample_quantities}")
print(f"NumPy array: {quantity_array}")
print(f"Shape: {quantity_array.shape}")
print(f"Dimensions: {quantity_array.ndim}")
print(f"Data type: {quantity_array.dtype}")

Python list: [2, 1, 2, 1]
NumPy array: [2 1 2 1]
Shape: (4,)
Dimensions: 1
Data type: int64

**Expected output (the exact integer dtype may vary by platform):**
```text
Python list: [2, 1, 2, 1]
NumPy array: [2 1 2 1]
Shape: (4,)
Dimensions: 1
```

The array contains four elements and has one dimension. NumPy arrays usually contain values of a compatible data type.

## 3. NumPy arrays

Create arrays with `np.array()`. Inspect `.shape`, `.ndim`, `.size`, and `.dtype` to understand the data's structure.

In [6]:
quantities = np.array([2, 1, 2, 1])
unit_prices = np.array([24.99, 79.50, 28.75, 34.00])

print(f"Quantity shape: {quantities.shape}")
print(f"Number of dimensions: {quantities.ndim}")
print(f"Number of values: {quantities.size}")
print(f"Price dtype: {unit_prices.dtype}")

Quantity shape: (4,)
Number of dimensions: 1
Number of values: 4
Price dtype: float64

### Vectorized calculations

Vectorization applies an operation across an array without writing an explicit Python loop. Corresponding positions should refer to the same business record.

In [7]:
line_totals = quantities * unit_prices

print(line_totals)
print(f"Total line value: ${line_totals.sum():.2f}")
print(f"Average line value: ${line_totals.mean():.2f}")

[49.98 79.5  57.5  34.  ]
Total line value: $220.98
Average line value: $55.24

**Expected output**
```text
[49.98 79.5  57.5  34.  ]
Total line value: $220.98
```

### Indexing, slicing, and Boolean filtering

NumPy arrays support indexing and slicing. A Boolean condition can select only the values that meet a rule.

In [8]:
print(f"First line total: ${line_totals[0]:.2f}")
print(f"First two totals: {line_totals[:2]}")
print(f"Totals above $50: {line_totals[line_totals > 50]}")

First line total: $49.98
First two totals: [49.98 79.5 ]
Totals above $50: [79.5 57.5]

**Exercise 3A**
Create a NumPy array from `[10, 15, 8, 20]`. Print its shape, multiply every value by 2, and select values greater than 10.

## 4. Pandas DataFrames

A **DataFrame** is a labeled table. Each column is a Pandas `Series`. A dictionary of lists is a convenient way to create a DataFrame; the lists must have matching lengths.

In [9]:
mini_catalogue = pd.DataFrame({
    "product": ["Wireless Mouse", "USB-C Hub", "Desk Lamp"],
    "category": ["Accessories", "Accessories", "Home"],
    "unit_price": [24.99, 34.00, 28.75]
})

display(mini_catalogue)
print(f"Shape: {mini_catalogue.shape}")
print(f"Columns: {mini_catalogue.columns.tolist()}")

          product     category  unit_price
0  Wireless Mouse  Accessories       24.99
1       USB-C Hub  Accessories       34.00
2       Desk Lamp         Home       28.75

Shape: (3, 3)
Columns: ['product', 'category', 'unit_price']

### Rows, columns, index, and shape
- Rows represent records.
- Columns represent fields or variables.
- The index labels rows.
- `shape` returns `(number_of_rows, number_of_columns)`.

**Exercise 4A:** Create a DataFrame called `inventory` with columns `product`, `stock`, and `reorder_level` for two products. Print its shape and column names.

## 5. Inspect a dataset before analysis

Inspecting the data is an essential first step. Useful attributes and methods include:
- `head()` / `tail()` — preview rows.
- `shape` — number of rows and columns.
- `columns` — column labels.
- `dtypes` — data types.
- `info()` — data types and non-null counts.
- `describe()` — numeric summary statistics.

In [10]:
print(f"Shape: {orders.shape}")
print(f"Columns: {orders.columns.tolist()}")
print("\nData types:")
print(orders.dtypes)
display(orders.head())

Shape: (8, 7)
Columns: ['order_id', 'customer', 'category', 'product', 'quantity', 'unit_price', 'status']

Data types:
order_id       object
customer       object
category       object
product        object
quantity        int64
unit_price    float64
status         object
dtype: object

,order_id,customer,category,product,quantity,unit_price,status
0,AW-4101,Maya Chen,Accessories,Wireless Mouse,2,24.99,Shipped
1,AW-4102,Omar Saleh,Electronics,Mechanical Keyboard,1,79.50,Processing
2,AW-4103,Lina Haddad,Home,Desk Lamp,2,28.75,Shipped
3,AW-4104,Noah Reed,Accessories,USB-C Hub,1,34.00,Cancelled
4,AW-4105,Maya Chen,Electronics,Headphones,1,59.99,Processing

In [11]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    8 non-null      object
 1   customer    8 non-null      object
 2   category    8 non-null      object
 3   product     8 non-null      object
 4   quantity    8 non-null      int64
 5   unit_price  8 non-null      float64
 6   status      8 non-null      object
dtypes: float64(1), int64(1), object(5)
memory usage: 580.0+ bytes

In [12]:
display(orders.describe())

       quantity  unit_price
count  8.000000     8.00000
mean   1.750000    41.74750
std    0.707107    18.71533
min    1.000000    24.99000
25%    1.000000    28.75000
50%    2.000000    36.50000
75%    2.000000    44.24750
max    3.000000    79.50000

`info()` helps identify missing values through non-null counts. `describe()` summarizes numeric columns, but it does not explain the business meaning of each value.

**Exercise 5A:** How many rows and columns does `orders` contain? Which columns are numeric, and which contain text categories?

## 6. Selecting columns and rows

Select one column with `orders["product"]` and several columns with a list of names: `orders[["order_id", "product"]]`.

- `.loc` selects using index labels.
- `.iloc` selects using integer positions.

The default index begins at zero, but labels and positions are not always the same.

In [13]:
display(orders[["order_id", "product", "status"]].head())

print("First row by position:")
display(orders.iloc[0])

print("Index labels 1 through 3:")
display(orders.loc[1:3, ["order_id", "customer", "status"]])

  order_id              product      status
0  AW-4101       Wireless Mouse     Shipped
1  AW-4102  Mechanical Keyboard  Processing
2  AW-4103            Desk Lamp     Shipped
3  AW-4104            USB-C Hub   Cancelled
4  AW-4105           Headphones  Processing

First row by position:

order_id             AW-4101
customer           Maya Chen
category         Accessories
product       Wireless Mouse
quantity                   2
unit_price             24.99
status               Shipped
Name: 0, dtype: object

Index labels 1 through 3:

  order_id     customer      status
1  AW-4102   Omar Saleh  Processing
2  AW-4103  Lina Haddad     Shipped
3  AW-4104    Noah Reed   Cancelled

**Important:** `.loc` uses label-based slicing and includes the ending label when present. `.iloc` uses integer positions and excludes the stop position, like ordinary Python slicing.

**Exercise 6A:** Display `order_id` and `status` for the first three rows using `.iloc`. Then display `product` and `unit_price` for index labels 2 through 4 using `.loc`.

## 7. Filtering rows

Filtering selects records that meet a condition. Use parentheses around each condition when combining them with `&` (AND) or `|` (OR). Do not use Python's `and` or `or` directly between Pandas Series.

In [14]:
processing_orders = orders[orders["status"] == "Processing"]
display(processing_orders[["order_id", "customer", "product", "status"]])

  order_id    customer              product      status
1  AW-4102  Omar Saleh  Mechanical Keyboard  Processing
4  AW-4105   Maya Chen           Headphones  Processing
6  AW-4107  Omar Saleh         Laptop Stand  Processing
7  AW-4107  Omar Saleh         Laptop Stand  Processing

In [15]:
premium_processing = orders[
    (orders["status"] == "Processing") &
    (orders["unit_price"] >= 50)
]
display(premium_processing[["order_id", "product", "unit_price", "status"]])

  order_id              product  unit_price      status
1  AW-4102  Mechanical Keyboard       79.50  Processing
4  AW-4105           Headphones       59.99  Processing

In [16]:
selected_categories = orders[orders["category"].isin(["Home", "Electronics"])]
display(selected_categories[["order_id", "category", "product"]])

  order_id     category              product
1  AW-4102  Electronics  Mechanical Keyboard
2  AW-4103         Home            Desk Lamp
4  AW-4105  Electronics           Headphones
5  AW-4106         Home            Desk Lamp

**Exercise 7A:** Create one DataFrame containing only `"Shipped"` orders. Create another containing orders where `quantity >= 2` and `status == "Shipped"`.

## 8. Creating and transforming columns

A new column can be calculated from existing columns. This is a common data-preparation operation.

Here, `line_total` is a simplified order-line value before discounts, tax, returns, and other adjustments.

In [17]:
orders["line_total"] = orders["quantity"] * orders["unit_price"]
display(orders[["order_id", "product", "quantity", "unit_price", "line_total"]])

  order_id              product  quantity  unit_price  line_total
0  AW-4101       Wireless Mouse         2       24.99       49.98
1  AW-4102  Mechanical Keyboard         1       79.50       79.50
2  AW-4103            Desk Lamp         2       28.75       57.50
3  AW-4104            USB-C Hub         1       34.00       34.00
4  AW-4105           Headphones         1       59.99       59.99
5  AW-4106            Desk Lamp         3       28.75       86.25
6  AW-4107         Laptop Stand         2       39.00       78.00
7  AW-4107         Laptop Stand         2       39.00       78.00

Use `np.where(condition, value_if_true, value_if_false)` for a simple vectorized two-way rule.

In [18]:
orders["value_band"] = np.where(
    orders["line_total"] >= 100,
    "High line value",
    "Standard line value"
)
display(orders[["order_id", "line_total", "value_band"]])

  order_id  line_total           value_band
0  AW-4101       49.98  Standard line value
1  AW-4102       79.50  Standard line value
2  AW-4103       57.50  Standard line value
3  AW-4104       34.00  Standard line value
4  AW-4105       59.99  Standard line value
5  AW-4106       86.25  Standard line value
6  AW-4107       78.00  Standard line value
7  AW-4107       78.00  Standard line value

**Business note:** `value_band` describes a line, not the full order. Clear column names reduce ambiguity.

**Exercise 8A:** Create `is_multi_unit`, which is `True` when `quantity > 1` and `False` otherwise.

## 9. Missing values and duplicates

Real datasets can contain missing or repeated records. First identify the issue, then choose a handling strategy based on business meaning.

Useful Pandas methods:
- `isna()` and `isna().sum()` — detect and count missing values.
- `fillna()` — replace missing values.
- `dropna()` — remove rows with missing values.
- `duplicated()` — identify duplicate rows.
- `drop_duplicates()` — remove duplicate rows.

In [19]:
orders_quality = orders.copy()
orders_quality.loc[2, "customer"] = None

print("Missing values by column:")
print(orders_quality.isna().sum())

Missing values by column:
order_id      0
customer      1
category      0
product       0
quantity      0
unit_price    0
status        0
line_total    0
value_band    0
dtype: int64

Do not automatically replace missing values without considering what they mean. For example, `"Unknown"` can be useful for a report, but it does not recover a customer's real identity.

In [20]:
orders_quality["customer"] = orders_quality["customer"].fillna("Unknown")
display(orders_quality.loc[2, ["order_id", "customer"]])

order_id    AW-4103
customer    Unknown
Name: 2, dtype: object

### Detect duplicates

The sample intentionally repeats order `AW-4107`. In a real order system, one order may contain multiple product lines, so `order_id` alone is not always a unique line identifier. Here, the repeated row is an accidental duplicate for teaching purposes.

In [21]:
duplicate_ids = orders[orders.duplicated(subset=["order_id"], keep=False)]
display(duplicate_ids[["order_id", "customer", "product", "quantity"]])

orders_deduplicated = orders.drop_duplicates()
print(f"Rows before: {len(orders)}")
print(f"Rows after: {len(orders_deduplicated)}")

  order_id    customer       product  quantity
6  AW-4107  Omar Saleh  Laptop Stand         2
7  AW-4107  Omar Saleh  Laptop Stand         2

Rows before: 8
Rows after: 7

**Exercise 9A:** Copy `orders`, set one `unit_price` to `NaN`, count missing values, then fill the missing value with a clearly chosen placeholder or remove that row. Explain your choice.

## 10. Grouping and business summaries

`groupby()` follows a **split–apply–combine** pattern: split rows into groups, calculate a summary for each group, and combine the results.

This is useful for comparing categories, products, and order statuses.

In [22]:
category_summary = (
    orders.groupby("category", as_index=False)
    .agg(
        order_lines=("order_id", "count"),
        units_sold=("quantity", "sum"),
        line_value=("line_total", "sum")
    )
    .sort_values("line_value", ascending=False)
)
display(category_summary)

      category  order_lines  units_sold  line_value
0  Accessories            4           7      239.98
2         Home            2           5      143.75
1  Electronics            2           2      139.49

**Interpretation:** This is a summary of order lines, units, and simplified line value by category. The sample includes a duplicate and a cancelled order, so these numbers are for learning only. An official revenue report needs explicit rules for duplicates, cancellations, returns, discounts, and tax.

In [23]:
status_summary = (
    orders.groupby("status", as_index=False)
    .agg(
        order_lines=("order_id", "count"),
        line_value=("line_total", "sum")
    )
    .sort_values("order_lines", ascending=False)
)
display(status_summary)

       status  order_lines  line_value
1  Processing            4      295.49
2     Shipped            3      193.73
0   Cancelled            1       34.00

**Exercise 10A:** Group by `product`, calculate total units and line value, then sort from highest to lowest units sold.

## 11. CSV input and output

CSV is a common text format for tabular data. Pandas uses `to_csv()` to write a DataFrame and `read_csv()` to load a CSV file.

The notebook creates its own local file; no external dataset is needed.

In [24]:
from pathlib import Path

data_folder = Path("adventureworks_data")
data_folder.mkdir(exist_ok=True)
csv_path = data_folder / "orders_unit06.csv"

orders.to_csv(csv_path, index=False)
print(f"Saved: {csv_path}")

Saved: adventureworks_data/orders_unit06.csv

`index=False` prevents Pandas from writing the DataFrame index as an extra column when it is not part of the business data.

In [25]:
orders_loaded = pd.read_csv(csv_path)

print(f"Loaded shape: {orders_loaded.shape}")
print("Loaded data types:")
print(orders_loaded.dtypes)
display(orders_loaded.head())

Loaded shape: (8, 9)
Loaded data types:
order_id       object
customer       object
category       object
product        object
quantity        int64
unit_price    float64
status         object
line_total    float64
value_band     object
dtype: object

,order_id,customer,category,product,quantity,unit_price,status,line_total,value_band
0,AW-4101,Maya Chen,Accessories,Wireless Mouse,2,24.99,Shipped,49.98,Standard line value
1,AW-4102,Omar Saleh,Electronics,Mechanical Keyboard,1,79.50,Processing,79.50,Standard line value
2,AW-4103,Lina Haddad,Home,Desk Lamp,2,28.75,Shipped,57.50,Standard line value
3,AW-4104,Noah Reed,Accessories,USB-C Hub,1,34.00,Cancelled,34.00,Standard line value
4,AW-4105,Maya Chen,Electronics,Headphones,1,59.99,Processing,59.99,Standard line value

CSV stores values as text. Pandas infers data types when reading the file, so inspect `dtypes` after loading.

## 12. Integrated AdventureWorks challenge

The business analyst needs a quick operations report.

### Tasks
1. Inspect the shape, column names, and data types.
2. Create `line_total = quantity * unit_price`.
3. Filter orders with status `"Processing"`.
4. Create a `value_band` for line values of at least `$100`.
5. In a copy of the data, count and handle a missing value.
6. Identify duplicate rows and create a deduplicated copy.
7. Group by category and calculate total units and line value.
8. Export the cleaned table to CSV, reload it, and verify the shape.

### Acceptance criteria
- Use Pandas operations instead of manually processing rows.
- Keep the original data available while cleaning.
- Explain each cleaning decision.
- Use readable names and explain why this summary is not automatically official revenue.

## 13. Instructor answer key

> **Instructor use:** Give learners time to complete the challenge before reviewing this solution.

In [26]:
# Reference solution — AdventureWorks data preparation
challenge = orders.copy()

challenge["line_total"] = challenge["quantity"] * challenge["unit_price"]
challenge["value_band"] = np.where(
    challenge["line_total"] >= 100,
    "High line value",
    "Standard line value"
)

processing = challenge[challenge["status"] == "Processing"].copy()

quality_check = challenge.copy()
quality_check.loc[0, "customer"] = None
missing_counts = quality_check.isna().sum()
quality_check["customer"] = quality_check["customer"].fillna("Unknown")

duplicates = challenge[challenge.duplicated(keep=False)]
cleaned = challenge.drop_duplicates().copy()

category_solution = (
    cleaned.groupby("category", as_index=False)
    .agg(units_sold=("quantity", "sum"), line_value=("line_total", "sum"))
    .sort_values("line_value", ascending=False)
)

output_folder = Path("adventureworks_data")
output_folder.mkdir(exist_ok=True)
solution_path = output_folder / "orders_unit06_solution.csv"
cleaned.to_csv(solution_path, index=False)
reloaded = pd.read_csv(solution_path)

print(f"Processing rows: {len(processing)}")
print(f"Duplicate rows flagged: {len(duplicates)}")
print(f"Rows after deduplication: {len(cleaned)}")
print(f"Missing customer values before fill: {missing_counts['customer']}")
print(f"Reloaded shape: {reloaded.shape}")
display(category_solution)

Processing rows: 4
Duplicate rows flagged: 2
Rows after deduplication: 7
Missing customer values before fill: 1
Reloaded shape: (7, 9)

      category  units_sold  line_value
0  Accessories           5      161.98
2         Home           5      143.75
1  Electronics           2      139.49